function Home() {

    return <div> <h1>Home 3</h1>
        <table>
            <thead>
                <th>Nome</th>
                <th>Idade</th>
                <th>Telefone</th>
            </thead>
            <tbody>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
                <tr>
                    <td>Coxe</td>
                    <td>29</td>
                    <td>923435472</td>
                </tr>
            </tbody>
        </table>
    </div>
}

export default Home